
name: Deploy to GH Pages

on:
  push:
    branches: ["master"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/git
            ~/.cargo/registry
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: jetli/trunk-action@v0.5.0
        with:
          version: "latest"
      - run: rustup target add wasm32-unknown-unknown
      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm install
      - run: npx @tailwindcss/cli -i ./styles/main.css -o ./styles/output.css --minify 
      - run: trunk build --release
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist/"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4